spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/viewboard?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234