spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.250.51/viewboard?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: wns
    password: 1234
  resources:
    static-locations: classpath:/static/
comm:
  uploadPath: "C:\\Users\\admin\\Desktop\\viewBoard-master\\src\\main\\resources\\static\\img"